### ISSUE TITLE
🚀 Feature: ClamAV custom connection

### ISSUE THREAD

**Issue by vanhyr** [stonith404/pingvin-share#152]
### 🔖 Feature description

The connection to the `ClamAV` daemon is **hardcoded** to use `clamav` as the host and `3310` as the port, it could be nice to have an option to specify another **host** and **port** for the connection.

### 🎤 Pitch

It could be configured as **environment variables** so that the user can define both the **host** and the **port** for the `ClamAV` connection.

The docker compose environment variables could look like:

```yaml
  environment:
    CLAMAV_HOST: "clamav" # host ip, domain or container name within the same docker network (default is clamav)
    CLAMAV_PORT: "3310" # custom port (default is 3310)
```
