### ISSUE TITLE
Visiting Webseite with HTTP and not HTTPS

### ISSUE THREAD

**Issue by Smallinger** [stonith404/pingvin-share#22]
I write on the Environment of my docker container a https://URL but if you visit the website only on http the links are all http and not catching from the APP_URL= environment, a better checking for that can be cool.
after making a Force on HTTPS all is working.

**Comment by stonith404** [comment]
That's strange, for me it works. Did you run `docker-compose up -d` after changing your `.env` file?

**Comment by Smallinger** [comment]
yeah i use a Docker-Compose file and set there all environments like

```
version: '3.8'
services:
  pingvin-share:
    container_name: pingvin-share
    image: stonith404/pingvin-share
    restart: unless-stopped
    environment:
      - APP_URL=https://DOMAIN
      - SHOW_HOME_PAGE=false
      - ALLOW_REGISTRATION=false
      - MAX_FILE_SIZE=524288000
      - JWT_SECRET=???????????????????????
    volumes:
      - "/root/pingvin-data/:/opt/app/backend/data"
networks:
  default:
    name: nginx-proxy
    external: true
```
i use Nginx-Proxy-Manager for a [Reverse Proxy](https://de.wikipedia.org/wiki/Reverse_Proxy) so that i need no port publishing.
