### ISSUE TITLE
❓ Question: http://localhost:3000/upload

### ISSUE THREAD

**Issue by antitiron** [stonith404/pingvin-share#220]
### 🙋‍♂️ Question

Hello!

Thank you for a great product.

However, a problem has now arisen. I have updated the contjner to a new version and suddenly when I go to the url it redirects to http://localhost:3000/upload.

Can you help?

```
version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    container_name: pingvin-share
    restart: unstopped
    ports:
      - 3000:3000
    volumes:
      - /data/docker/pingvin-share/data:/opt/app/backend/data
      - /data/docker/pingvin-share/data/images:/opt/app/frontend/public/img
```
