### ISSUE TITLE
🐛 Bug Report: Initial Database Configuration Fails On Remote Drives

### ISSUE THREAD

**Issue by hardcore2031** [stonith404/pingvin-share#317]
### 👟 Reproduction steps

I am using docker compose to try and deploy pingvin share.  I have a NAS system that has a share named prism that I have mounted on my docker host.  So for dockers which need remote storage (more than whats available on the docker host SSD) i can use /mnt/prism/  I have several containers set up in this fashion (qBittorrent, TubeArchivist, Arr apps, etc)

The docker compose file I used:

```
version: '3.8'
services:
  pingvin-share:
    container_name: pingvin
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3100:3000
    volumes:
      - "/mnt/prism/pingvin:/opt/app/backend/data"
      - "/mnt/prism/pingvin/images:/opt/app/frontend/public/img"
```

I added the container name, changed the port as my port 3000 is already in use, and changed the volumes to use the location on my NAS where I keep docker data. I'm a beginner with docker, but these are edits I've made before on other containers. I am using Portainer CE 2.19.1 to create the pingvin stack.

### 👍 Expected behavior

I expect the /mnt/prism/ path on the docker host to be able to be used just as any other local path, as it has for other containers.

### 👎 Actual Behavior

It deploys seemingly fine, and then on startup it seems to loop and restart. Logs show the application try and work on the SQLite db but it shows as locked. I've tried redeploying the container, rebooting the docker host, all to no avail.  The files (pingvin-share.db and pingvin-share.db-journal) are written without issue, and pingvin-share.db-journal grows to 1kb, but the pingvin-share.db file seems to be locked.

```
> pingvin-share-backend@0.20.1 prod
> prisma migrate deploy && prisma db seed && node dist/src/main
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
Listening on port 3333 url: http://0.0.0.0:3333
17 migrations found in prisma/migrations
Error: SQLite database error
database is locked
   0: sql_schema_connector::sql_migration_persistence::initialize
           with namespaces=None
             at schema-engine/connectors/sql-schema-connector/src/sql_migration_persistence.rs:14
   1: schema_core::state::ApplyMigrations
             at schema-engine/core/src/state.rs:197
```
I have redeployed with the volumes pointed to local directories like below and everything runs perfectly.  But then I am limited to files being no larger than what will fit on the tiny docker host ssd.
```
    volumes:
      - "/dockerdata/pingvin:/opt/app/backend/data"
      - "/dockerdata/pingvin/images:/opt/app/frontend/public/img"
```

Please let me know if any other information would be helpful.

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Yeah, mounting the SQLite database to a NAS doesn't work. But you can change your Docker Compose configuration so that the SQLite file is mounted to your physical drive and the uploaded file to the NAS. The SQLite file is at most a few megabytes.

```yml
version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "/path-to-your-nas/pingvin-share-data:/opt/app/backend/data/uploads"
      - "/path-to-your-nas/pingvin-share-data:/opt/app/frontend/public/img"
      - "/path-to-a-physical-drive/db.sql:/opt/app/backend/data/pingvin-share.db"
```

Make sure a empty SQLite file already exists before you create the container: `touch /path-to-a-physical-drive/db.sql`

**Comment by hardcore2031** [comment]
Thank you for the reply.  Changed up my docker compose to this:
```
version: '3.8'
services:
  pingvin-share:
    container_name: pingvin
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3100:3000
    volumes:
      - "/mnt/prism/Downloads/pingvin:/opt/app/backend/data"
      - "/mnt/prism/Downloads/pingvin/images:/opt/app/frontend/public/img"
      - "/yacht/AppData/Config/pingvin/db.sql:/opt/app/backend/data/pingvin-share.db"
```
 I then did `sudo touch /yacht/AppData/Config/pingvin/db.sql` and then re-pulled the image and updated the stack.  It started then exited, with the log entry:
```
> pingvin-share-backend@0.20.1 prod
> prisma migrate deploy && prisma db seed && node dist/src/main
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
Error: P1013: The provided database string is invalid. Error parsing connection string: ../data/pingvin-share.db in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
Listening on port 3333 url: http://0.0.0.0:3333
```
I'm unsure if this means I need to specify the port in my connection string, or how I need to modify it to make the magic happen.
