### ISSUE TITLE
🐛 Bug Report: docker + pingvin v.0.21.5 + nginx proxy manager: 502 Bad Gateway

### ISSUE THREAD

**Issue by maurxce** [stonith404/pingvin-share#392]
### 👟 Reproduction steps

- create a container for pingvin:0.21.5 and use npm to route it
```yaml
# /nginx/compose.yml
services:
  nginx:
    image: jc21/nginx-proxy-manager:2.11.0
    restart: unless-stopped
    hostname: proxymanager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
```
```yaml
# /files/compose.yml
services:
  pingvin:
    image: stonith404/pingvin-share:v0.21.5
    restart: unless-stopped
    container_name: pingvin
    volumes:
      - ./data:/opt/app/backend/data
      - ./public:/opt/app/frontend/public
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
```

### 👍 Expected behavior

- it should display the pingvin instance

### 👎 Actual Behavior

- it returns status code 502

---

when first creating the pingvin container with `v0.21.0`, letting it create the directories, and then upgrading to `v0.21.5` works without any issues

### 🌐 Browser

Chrome Version 120.0.6099.225
