### ISSUE TITLE
🚀 Feature: The ability to customize port via docker_compose.yml

### ISSUE THREAD

**Issue by SteveDevOps** [stonith404/pingvin-share#413]
### 🔖 Feature description

It would be nice to have the ability to customize the port bound via docker_compose.yml. 3000 is a popular port chosen by opensource apps in general.

### 🎤 Pitch

If I could customize the bound port by container is use via a docker_compose.yml respected envar,, I could avoid conflicts with other containers using port 3000.

```
environment:
 - FE_PORT=3200
```

**Comment by dnielso5** [comment]
Edit this line in the .yml file

```
    ports:
      - ThePortYouWantHere:3000
```

**Comment by stonith404** [comment]
Can't you just change the exposed port in the `docker-compose.yml`?
```
    ports:
      - 3200:3000
```

Or I'm missing something?

**Comment by Today20092** [comment]
Do a docker compose like this, with the ports being like this 
In my example it is unchanged, but you could do 3001:3000
which means 3001 on the host is mapped to 3000 on the docker container.
```yml
ports:
  - host:application
```
the compose yml
```yml
version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
 ```
