### ISSUE TITLE
❓ Question: Configure Authelia

### ISSUE THREAD

**Issue by HugoFollic** [stonith404/pingvin-share#441]
### 🙋‍♂️ Question

Hi,

I tried to configure Pingvin to work with Authelia which I'm using as OIDC provider for my others app. Unfortunately I face an issue with the configuration probably.
Here

 is my config in Pingvin : 
![Capture d’écran 2024-04-05 235150](https://github.com/stonith404/pingvin-share/assets/65908936/14d3c425-b58f-4e72-99d1-9090ddd85060)

And here is my config in Authelia : 
```
client_id: pingvin
        client_name: WeTransfer alternative
        client_secret: secret
        consent_mode: implicit
        scopes:
          - openid
          - groups
          - profile
          - email
        redirect_uris:
          - https://send.myurl.com/api/oauth/callback/oidc
```

But when I click on the OIDC logo, it opens a new tabs (which normally shoudn't) to the url `https://send.myurl.com/api/oauth/auth/oidc` and an error 500 appears :
`{"statusCode":500,"message":"Internal server error"}`

Do you know where I'm wrong ?

Thanks
