### ISSUE TITLE
🐛 Bug Report: No Logo 

### ISSUE THREAD

**Issue by ipod86** [stonith404/pingvin-share#567]
### 👟 Reproduction steps

I installed Pingvin Share using the docker compose provided. 
I'm delighted. Everything works great. 

But I have one problem. The logo at the top left is not displayed. Neither after a fresh installation nor when uploading it myself. Both when accessing via the direct IP:Port and the reverse proxy.

### 👍 Expected behavior

See the logo 

### 👎 Actual Behavior

No Logo 

### 🌐 Browser

Chrome, Firefox, Samsung Internet (all mobile)

**Comment by ipod86** [comment]
![Screenshot_20240826_215646_Chrome](https://github.com/user-attachments/assets/17a0dea7-e218-4ab1-a520-8deade47fd72)

**Comment by stonith404** [comment]
Can you share the docker compose that you are using and the logs of the container? You can get the logs with `docker compose logs`.

**Comment by ipod86** [comment]
My docker compose

```
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3003:3000
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
```

In data images I also see the uploaded logo in 2 resolutions.

My log when starting (copied from portainer):

I just saw "no such file or directory" in the log. But it disappeared after I restarted the container and I can't see it anymore. However, the logo appeared after the restart. Very interesting.
