### ISSUE TITLE
🚀 Feature: Favicon 

### ISSUE THREAD

**Issue by ipod86** [stonith404/pingvin-share#579]
### 🔖 Feature description

Is it possible to customize the favicon to match the customized logo? 

When a link is sent for sharing with Apple Mail or some messengers (presumably the favicon) is used as a preview of the link.

### 🎤 Pitch

-

**Comment by stonith404** [comment]
The favicon should get replaced automatically with the logo that you've uploaded. You probably have to clear the cache to see the new favicon.

**Comment by ipod86** [comment]
I've tested it in the meantime. 

Under data/images I see the logo.png and favicon.ico with my uploaded image. 
But deleting the cache didn't help. If I then go into the Icons folder, I see various icons, but all with the penguin 🐧. 

If I replace it manually and delete the cache, I get the new favicon.

**Comment by stonith404** [comment]
Okay strange, I'm able to update the favicon on my instance without any problems. Can you share your docker compose file?

**Comment by ipod86** [comment]
It's exactly the example from git. I just adjusted the port.

```
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3003:3000
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
# Optional: If you add ClamAV, uncomment the following to have ClamAV start first.
#    depends_on:
#      clamav:
#        condition: service_healthy
# Optional: Add ClamAV (see README.md)  
# ClamAV is currently only available for AMD64 see https://github.com/Cisco-Talos/clamav/issues/482
#  clamav:
#    restart: unless-stopped
#    image: clamav/clamav
```
