### ISSUE TITLE
🐛 Bug Report: Health check fails if `CADDY_DISABLED` is set

### ISSUE THREAD

**Issue by marvinruder** [stonith404/pingvin-share#809]
### 👟 Reproduction steps

When I set `CADDY_DISABLED=true` and start the container

### 👍 Expected behavior

The container health check should succeed

### 👎 Actual Behavior

The container health check fails as `http://localhost:3000/api/health` is unavailable

### 📜 Logs

```
curl: (7) Failed to connect to localhost port 3000 after 0 ms: Could not connect to server
```

**Comment by stonith404** [comment]
You would have to override the health check in your `docker-compose.yml` to something like this:
```
 healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
