### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by itsTingu** [stonith404/pingvin-share#810]
### 👟 Reproduction steps

Hello, thank you creating this beautiful application. I have tried running the **docker** container on docker desktop and it is running fine. 

**Intalling the container on a VPS running Almalinux**

Background: I have installed Pangolin which  serves as first line of defense to authenticate the users before accessing the Pingvin application. However, I have encountered issues in exposing the Pingvin service alongside Pangolin.

The docker-compose file I am using is as follows:

```
name: pangolin
services:

  pingvin-share:
    image: stonith404/pingvin-share # or ghcr.io/stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3007
    environment:
      - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container
      - CADDY_DISABLED=true # Disable caddy
      - API_URL=http://127.0.0.1:8080
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
  #      - "./config.yaml:/opt/app/config.yaml" # Add this line, if you want to configure pingvin-share via config file and not via UI

  # To add ClamAV, to scan your shares for malicious files,
  # see https://stonith404.github.io/pingvin-share/setup/integrations/#clamav-docker-only


  pangolin:
    image: fosrl/pangolin:1.2.0
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 5

  gerbil:
    image: fosrl/gerbil:1.0.0
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode

  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped

    network_mode: service:gerbil # Ports appear on the gerbil service

    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
```

I have read a github issues page here where you need to change the `localhost` to `127.0.0.1` or the other way around with no success.

- I have changed the service port to map to `3000:3007` and the port did not map as expected.
- I have disabled caddy to make sure it doesn't conflict with Pangolin's Traefik container

Appreciate any support as I am inexperienced in troubleshooting

P.S: logs show no errors, but I'll share them if requested.

### 👍 Expected behavior

Expose the instance to the domain configured and show the WEB UI

executing the command `curl -l http://localhost:8080` should show an API output

### 👎 Actual Behavior

`$ curl -l http://localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused`
