### ISSUE TITLE
🐛 Bug Report: Issue with Pingvin and Authelia integration

### ISSUE THREAD

**Issue by manzerbredes** [stonith404/pingvin-share#815]
### 👟 Reproduction steps

When I try to link my pingvin account to authelia through OpenID: My account > Social login > OpenID > Link 

### 👍 Expected behavior

Being able to use my Pingvin account though Authelia/OpenID.

### 👎 Actual Behavior

It actually fails on the linking process _"Cannot get your user info from this OpenID Connect account."_.

![Image](https://github.com/user-attachments/assets/f2dee99e-e1ad-4a3e-bbe4-13bcc5b3b678)

In my Pingvin OpenID config, Everything is blank except "Client ID", "Client Secret", "OpenID Connect scope" and "OpenID Connect Discovery URI". 

- "OpenID Connect scope" is set to "openid email profile groups"
- "OpenID Connect Discovery URI" is set to "https://mysub.mydomain.com/.well-known/openid-configuration"

I have tried to set "OpenID Connect username claim" to "email" but no success.

### 📜 Logs

[Nest] 46  - 04/11/2025, 8:41:31 AM   ERROR [OidcProvider] Can not get username from ID Token {
  "amr": [
    "pwd",
    "kba"
  ],
  "at_hash": "....",
  "aud": [
    "pingvin"
  ],
  "auth_time": 00000,
  "azp": "pingvin",
  "exp": 0000,
  "iat": 000,
  "iss": "..",
  "jti": "...",
  "nonce": "...",
  "rat": 00000000,
  "sub": "....."
}
[Nest] 46  - 04/11/2025, 8:41:31 AM   ERROR [ErrorPageExceptionFilter] {"error":"cannot_get_user_info","params":["provider_oidc"]}

**Comment by manzerbredes** [comment]
After a couple of trials, I finally make it work!
For Authelia, setting "OpenID Connect username claim" to "sub" solved the issue.
Hope that others will find this useful.

**Comment by casse-boubou** [comment]
Hi, Thanks for the tips. 
"sub" allowed me to pass the error `" error ":" cannot_get_user_info "`
But just after came another mistake: `"error":"no_email"`
Do you also have this error about email with OIDC Authela?
Maybe I made a configuration error in Authelia? Could we compare our config please?
### Authelia
```
identity_providers:
  oidc:
    clients:
      ## Pingvin-Share
      - client_id: pingvinshare
        client_name: pingvinshare
        client_secret: MY_SECRET
        token_endpoint_auth_method: client_secret_post
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://MY_DOMAIN/api/oauth/callback/oidc
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        userinfo_signed_response_alg: 'none'
```
### Pingvin-share
```
oauth:
  allowRegistration: "true"
  ignoreTotp: "true"
  disablePassword: "false"
  oidc-enabled: "true"
  oidc-discoveryUri: "https://MY_AUTH_DOMAIN/.well-known/openid-configuration"
  oidc-signOut: "true"
  oidc-scope: openid email profile
  oidc-usernameClaim: "sub"
  oidc-rolePath: ""
  oidc-roleGeneralAccess: ""
  oidc-roleAdminAccess: "admins"
  oidc-clientId: "pingvinshare"
  oidc-clientSecret: "MY_SECRET"
```
