### ISSUE TITLE
🐛 Bug(?) Report: "Can't get email address" during account creation using OIDC with ZITADEL

### ISSUE THREAD

**Issue by sneexy-boi** [stonith404/pingvin-share#818]
### 👟 Reproduction steps

I'm having an issue setting up my self hosted ZITADEL to be used with Pingvin.

I can link existing accounts on Pingvin with ZITADEL and that works perfectly fine, but attempting to sign in with an account that doesn't already exist on the Pingvin side fails with "Can't get email address from this OpenID Connect account."

Setup should be correctly configured for Social login:
- `OpenID Connect Discovery URI` set to `https://zitadel.me.com/.well-known/openid-configuration`
- `OpenID Connect scope` set to `openid profile email`
- `OpenID Connect username claim` set to `sub` (Doesn't work at all if this isn't set)
- Rest is left blank, of course with `OpenID Connect Client ID` and `OpenID Connect Client secret` being set correctly.

### 👍 Expected behavior

When logging in using my ZITADEL account that doesn't exist/isn't linked with an account on Pingvin, it should create the account and log me in.

### 👎 Actual Behavior

Fails to sign me in with "Can't get email address from this OpenID Connect account."

### 📜 Logs

The only relevant line it spits out every time a failed attempt occurs:
```
[Nest] 61  - 04/18/2025, 6:36:14 PM   ERROR [ErrorPageExceptionFilter] {"error":"no_email","params":["provider_oidc"],"redirect":"/auth/signIn"}
```

**Comment by casse-boubou** [comment]
Hum i solve it in Authelia like this
```
identity_providers:
  oidc:
    .....
    claims_policies:
      pingvin_claims_policy:
        id_token: ['rat', 'groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
    .....
    clients:
      - client_id: pingvinshare
         .....
        claims_policy: 'pingvin_claims_policy'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
```
