### ISSUE TITLE
🚀 Feature: HTTPS

### ISSUE THREAD

**Issue by Ckotselis** [stonith404/pingvin-share#85]
### 🔖 Feature description

You should have the ability to put all behind https ..!!  

### 🎤 Pitch

How to do this with haproxy or other reverse proxy server to secure your shares..!!

**Comment by stonith404** [comment]
If you already have a reverse proxy, you can setup https for Pingvin Share like you would do it with other services. If not, I would recommend you to simply add a nginx container to your Docker compose stack, [see this tutorial](https://www.freecodecamp.org/news/docker-nginx-letsencrypt-easy-secure-reverse-proxy-40165ba3aee2/amp/).

I personally like Nginx Proxy Manager to do my reverse proxy stuff.

I don't plan to implement https directly in Pingvin Share as you can simply add a reverse proxy to the Docker compose stack.

**Comment by Hukuma1** [comment]
Just wanted to share how easily NPM can be deployed right next to Pigvin:

```
version: '3'
services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    ports:
      - "8181:8181"
      - "8080:8080"
      - "4443:4443"
    volumes:
      - "/docker/appdata/nginx-proxy-manager:/config:rw"
```
