### ISSUE TITLE
Suggestion: Add to Caprover on click apps repository.

### ISSUE THREAD

**Issue by sebastian-b00** [stonith404/pingvin-share#92]
Hi, this project is great, nice interface and it works.
I suggest that to give more scope to the project, it could be added to [Caprover on click apps repository](https://github.com/caprover/one-click-apps), the logo needs to be added, so I'm not sure if adding it by someone else is correct, due to copyright issues.
I have tried this and it might help:

```
captainVersion: 4
services:
    '$$cap_appname':
        image: stonith404/pingvin-share:$$cap_version
        volumes:
            - '$$cap_appname-data:/opt/app/backend/data'
        caproverExtra:
            containerHttpPort: '3000'
caproverOneClickApp:
    variables:
        - id: '$$cap_version'
          label: Pingvin Share Version
          defaultValue: 'v0.8.0'
          description: Check the Docker page for valid tags https://hub.docker.com/r/stonith404/pingvin-share/tags
    instructions:
        start: |-
            Pingvin Share is a file sharing platform.
            Github repository: https://github.com/stonith404/pingvin-share
        end: |-
            Pingvin Share has been successfully deployed!
            To start the initial setup go to http://$$cap_appname.$$cap_root_domain
            You can try to enable HTTPS from the "HTTP Settings" section of the application in the Caprover dashboard.
    displayName: Pingvin Share
    isOfficial: true
    description: Pingvin Share is a file sharing platform.
```

And forgive me if this is not the right place to make suggestions.
